# Generated by Django 4.0.2 on 2022-04-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_post_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
