# Generated by Django 4.0.2 on 2022-04-20 02:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0010_rename_option_report_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="price",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(
                        10000000, "Price must be less than 10000000"
                    )
                ],
            ),
        ),
    ]
