# Generated by Django 4.0.2 on 2022-03-23 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_pic", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "school",
                    models.CharField(
                        choices=[
                            ("tandon", "Tandon School of Engineering"),
                            ("tish", "Tisch School of Arts"),
                            ("stern", "Stern School of Business"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("address", models.CharField(default="", max_length=50)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
