# Generated by Django 4.0.2 on 2022-04-04 17:55

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=phone_field.models.PhoneField(
                blank=True, help_text="Contact phone number", max_length=31
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="school",
            field=models.CharField(
                choices=[
                    ("gsas", "Graduate School of Arts and Science"),
                    ("tandon", "Tandon School of Engineering"),
                    ("tish", "Tisch School of Arts"),
                    ("stern", "Stern School of Business"),
                ],
                default="",
                max_length=10,
            ),
        ),
    ]
