# Generated by Django 4.0.2 on 2022-04-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_profile_phone_profile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                default="https://nyu-marketplace-team1.s3.amazonaws.com/blank-profile-picture.webp",
                null=True,
                upload_to="",
            ),
        ),
    ]
