# Generated by Django 4.0.2 on 2022-04-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_profile_profile_pic"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="phone_number",),
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="blank-profile-picture.webp",
                null=True,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="school",
            field=models.CharField(
                choices=[
                    ("tandon", "Tandon School of Engineering"),
                    ("tish", "Tisch School of Arts"),
                    ("stern", "Stern School of Business"),
                ],
                default="",
                max_length=10,
            ),
        ),
    ]
