language: python
os: linux

python:
  - 3.8

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py collectstatic

script:
  - python -m black . --check
  - python -m flake8 --max-line-length=150
  - coverage run --source=. manage.py test

after_success:
  - python -m coveralls